### PR TITLE
Always emit NoopSpans if the tracer extension is disabled

### LINKED ISSUE #1474: [BUG] Exception in forked CLI process with DD_TRACE_CLI_ENABLED=true
### Bug description
The following code with `DD_TRACE_CLI_ENABLED=true` cause Exception.
I know CLI with `pcntl_fork()` is not supported, but I expect `Noop` class.

```
<?php
require("vendor/autoload.php");

use DDTrace\GlobalTracer;

$pid = pcntl_fork();
if ($pid == -1) {
    return;
}
if ($pid) {
    // parent
    sleep(2);
} else {
    // child
    $tracer = GlobalTracer::get();
    if ($tracer) {
        $scope = $tracer->startActiveSpan("test");
    }

    posix_kill(posix_getpid(), SIGTERM);
}
```
```
$ DD_TRACE_CLI_ENABLED=true php ./test.php 
PHP Warning:  Creating default object from empty value in /usr/share/pear/datadog_trace/bridge/_generated_internal.php on line 689
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to DDTrace\Span::__construct() must be an instance of DDTrace\SpanData, instance of stdClass given, called in /usr/share/pear/datadog_trace/bridge/_generated_internal.php on line 698 and defined in /usr/share/pear/datadog_trace/bridge/_generated_internal.php:396
Stack trace:
#0 /usr/share/pear/datadog_trace/bridge/_generated_internal.php(698): DDTrace\Span->__construct()
#1 /usr/share/pear/datadog_trace/bridge/_generated_internal.php(750): DDTrace\Tracer->startSpan()
#2 /usr/src/work/tokioka/test.php(17): DDTrace\Tracer->startActiveSpan()
#3 {main}
  thrown in /usr/share/pear/datadog_trace/bridge/_generated_internal.php on line 396
```

### PHP version
```
$ php -v
PHP 7.4.25 (cli) (built: Oct 19 2021 15:18:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.25, Copyright (c), by Zend Technologies
    with ddtrace v0.67.0, Copyright Datadog, by Datadog
```

### Tracer version
```
$ php -r "echo phpversion('ddtrace').PHP_EOL;"
0.67.0
```

### Installed extensions
```
$ php -m
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
ddtrace
dom
exif
fileinfo
filter
ftp
gd
gettext
grpc
hash
iconv
igbinary
intl
json
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
ssh2
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
ddtrace
```

### OS info
```
$ cat /etc/os-release | grep -E "(NAME)|(VERSION)"
NAME="CentOS Linux"
VERSION="7 (Core)"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
CPE_NAME="cpe:/o:centos:centos:7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

#### Output of phpinfo() (ddtrace >= 0.47.0)
```
]$ php --ri=ddtrace

ddtrace


Datadog PHP tracer extension
For help, check out the documentation at https://docs.datadoghq.com/tracing/languages/php/
(c) Datadog 2020

Datadog tracing support => disabled
Version => 0.67.0
DATADOG TRACER CONFIGURATION => {"date":"2022-01-24T07:12:31Z","os_name":"Linux docker-desktop 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64","os_version":"5.10.47-linuxkit","version":"0.67.0","lang":"php","lang_version":"7.4.25","env":null,"enabled":true,"service":"mercari-api-jp","enabled_cli":false,"agent_url":"http://localhost:8126","debug":false,"analytics_enabled":false,"sample_rate":1.000000,"sampling_rules":null,"tags":{},"service_mapping":{},"distributed_tracing_enabled":true,"priority_sampling_enabled":true,"dd_version":"master-20220120070113","architecture":"x86_64","sapi":"cli","datadog.trace.request_init_hook":"/usr/share/pear/datadog_trace/bridge/dd_wrap_autoloader.php","open_basedir_configured":false,"uri_fragment_regex":null,"uri_mapping_incoming":null,"uri_mapping_outgoing":null,"auto_flush_enabled":false,"generate_root_span":true,"http_client_split_by_domain":false,"measure_compile_time":true,"report_hostname_on_root_span":false,"traced_internal_functions":null,"auto_prepend_file_configured":false,"integrations_disabled":"default","enabled_from_env":false,"opcache.file_cache":null,"agent_error":"Failed connect to localhost:8126; Connection refused"}

                               Diagnostics                               
agent_error => Failed connect to localhost:8126; Connection refused
Diagnostic checks => failed

Directive => Local Value => Master Value
ddtrace.disable => Off => Off
ddtrace.cgroup_file => /proc/self/cgroup => /proc/self/cgroup
datadog.trace.request_init_hook => /usr/share/pear/datadog_trace/bridge/dd_wrap_autoloader.php => /usr/share/pear/datadog_trace/bridge/dd_wrap_autoloader.php
ddtrace.request_init_hook => /usr/share/pear/datadog_trace/bridge/dd_wrap_autoloader.php => /usr/share/pear/datadog_trace/bridge/dd_wrap_autoloader.php
datadog.trace.agent_url => no value => no value
datadog.agent_host => localhost => localhost
datadog.distributed_tracing => On => On
datadog.dogstatsd_port => 8125 => 8125
datadog.env => no value => no value
datadog.autofinish_spans => Off => Off
datadog.trace.url_as_resource_names_enabled => On => On
datadog.integrations_disabled => default => default
datadog.priority_sampling => On => On
datadog.service => mercari-api-jp => mercari-api-jp
datadog.service_name => mercari-api-jp => mercari-api-jp
datadog.service_mapping => no value => no value
datadog.tags => no value => no value
datadog.trace.global_tags => no value => no value
datadog.trace.agent_port => 8126 => 8126
datadog.trace.analytics_enabled => Off => Off
datadog.trace.auto_flush_enabled => Off => Off
datadog.trace.cli_enabled => Off => Off
datadog.trace.measure_compile_time => On => On
datadog.trace.debug => Off => Off
datadog.trace.enabled => Off => On
datadog.trace.health_metrics_enabled => Off => Off
datadog.trace.health_metrics_heartbeat_sample_rate => 0.001 => 0.001
datadog.trace.http_client_split_by_domain => Off => Off
datadog.trace.memory_limit => no value => no value
datadog.trace.report_hostname => Off => Off
datadog.trace.resource_uri_fragment_regex => no value => no value
datadog.trace.resource_uri_mapping_incoming => no value => no value
datadog.trace.resource_uri_mapping_outgoing => no value => no value
datadog.trace.sample_rate => 1 => 1
datadog.sampling_rate => 1 => 1
datadog.trace.sampling_rules => no value => no value
datadog.trace.header_tags => no value => no value
datadog.trace.traced_internal_functions => no value => no value
datadog.trace.agent_timeout => 500 => 500
datadog.trace.agent_connect_timeout => 100 => 100
datadog.trace.debug_prng_seed => -1 => -1
datadog.log_backtrace => Off => Off
datadog.trace.generate_root_span => On => On
datadog.trace.spans_limit => 1000 => 1000
datadog.trace.agent_max_consecutive_failures => 3 => 3
datadog.trace.agent_attempt_retry_time_msec => 5000 => 5000
datadog.trace.bgs_connect_timeout => 2000 => 2000
datadog.trace.bgs_timeout => 5000 => 5000
datadog.trace.agent_flush_interval => 5000 => 5000
datadog.trace.agent_flush_after_n_requests => 10 => 10
datadog.trace.shutdown_timeout => 5000 => 5000
datadog.trace.startup_logs => On => On
datadog.trace.agent_debug_verbose_curl => Off => Off
datadog.trace.debug_curl_output => Off => Off
datadog.trace.beta_high_memory_pressure_percent => 80 => 80
datadog.trace.warn_legacy_dd_trace => On => On
datadog.trace.retain_thread_capabilities => Off => Off
datadog.version => master-20220120070113 => master-20220120070113
datadog.trace.cakephp_enabled => On => On
datadog.trace.cakephp_analytics_enabled => Off => Off
datadog.cakephp_analytics_enabled => Off => Off
datadog.trace.cakephp_analytics_sample_rate => 1 => 1
datadog.cakephp_analytics_sample_rate => 1 => 1
datadog.trace.codeigniter_enabled => On => On
datadog.trace.codeigniter_analytics_enabled => Off => Off
datadog.codeigniter_analytics_enabled => Off => Off
datadog.trace.codeigniter_analytics_sample_rate => 1 => 1
datadog.codeigniter_analytics_sample_rate => 1 => 1
datadog.trace.curl_enabled => On => On
datadog.trace.curl_analytics_enabled => Off => Off
datadog.curl_analytics_enabled => Off => Off
datadog.trace.curl_analytics_sample_rate => 1 => 1
datadog.curl_analytics_sample_rate => 1 => 1
datadog.trace.elasticsearch_enabled => On => On
datadog.trace.elasticsearch_analytics_enabled => Off => Off
datadog.elasticsearch_analytics_enabled => Off => Off
datadog.trace.elasticsearch_analytics_sample_rate => 1 => 1
datadog.elasticsearch_analytics_sample_rate => 1 => 1
datadog.trace.eloquent_enabled => On => On
datadog.trace.eloquent_analytics_enabled => Off => Off
datadog.eloquent_analytics_enabled => Off => Off
datadog.trace.eloquent_analytics_sample_rate => 1 => 1
datadog.eloquent_analytics_sample_rate => 1 => 1
datadog.trace.guzzle_enabled => On => On
datadog.trace.guzzle_analytics_enabled => Off => Off
datadog.guzzle_analytics_enabled => Off => Off
datadog.trace.guzzle_analytics_sample_rate => 1 => 1
datadog.guzzle_analytics_sample_rate => 1 => 1
datadog.trace.laravel_enabled => On => On
datadog.trace.laravel_analytics_enabled => Off => Off
datadog.laravel_analytics_enabled => Off => Off
datadog.trace.laravel_analytics_sample_rate => 1 => 1
datadog.laravel_analytics_sample_rate => 1 => 1
datadog.trace.lumen_enabled => On => On
datadog.trace.lumen_analytics_enabled => Off => Off
datadog.lumen_analytics_enabled => Off => Off
datadog.trace.lumen_analytics_sample_rate => 1 => 1
datadog.lumen_analytics_sample_rate => 1 => 1
datadog.trace.memcached_enabled => On => On
datadog.trace.memcached_analytics_enabled => Off => Off
datadog.memcached_analytics_enabled => Off => Off
datadog.trace.memcached_analytics_sample_rate => 1 => 1
datadog.memcached_analytics_sample_rate => 1 => 1
datadog.trace.mongo_enabled => On => On
datadog.trace.mongo_analytics_enabled => Off => Off
datadog.mongo_analytics_enabled => Off => Off
datadog.trace.mongo_analytics_sample_rate => 1 => 1
datadog.mongo_analytics_sample_rate => 1 => 1
datadog.trace.mongodb_enabled => On => On
datadog.trace.mongodb_analytics_enabled => Off => Off
datadog.mongodb_analytics_enabled => Off => Off
datadog.trace.mongodb_analytics_sample_rate => 1 => 1
datadog.mongodb_analytics_sample_rate => 1 => 1
datadog.trace.mysqli_enabled => On => On
datadog.trace.mysqli_analytics_enabled => Off => Off
datadog.mysqli_analytics_enabled => Off => Off
datadog.trace.mysqli_analytics_sample_rate => 1 => 1
datadog.mysqli_analytics_sample_rate => 1 => 1
datadog.trace.nette_enabled => On => On
datadog.trace.nette_analytics_enabled => Off => Off
datadog.nette_analytics_enabled => Off => Off
datadog.trace.nette_analytics_sample_rate => 1 => 1
datadog.nette_analytics_sample_rate => 1 => 1
datadog.trace.pdo_enabled => On => On
datadog.trace.pdo_analytics_enabled => Off => Off
datadog.pdo_analytics_enabled => Off => Off
datadog.trace.pdo_analytics_sample_rate => 1 => 1
datadog.pdo_analytics_sample_rate => 1 => 1
datadog.trace.phpredis_enabled => On => On
datadog.trace.phpredis_analytics_enabled => Off => Off
datadog.phpredis_analytics_enabled => Off => Off
datadog.trace.phpredis_analytics_sample_rate => 1 => 1
datadog.phpredis_analytics_sample_rate => 1 => 1
datadog.trace.predis_enabled => On => On
datadog.trace.predis_analytics_enabled => Off => Off
datadog.predis_analytics_enabled => Off => Off
datadog.trace.predis_analytics_sample_rate => 1 => 1
datadog.predis_analytics_sample_rate => 1 => 1
datadog.trace.slim_enabled => On => On
datadog.trace.slim_analytics_enabled => Off => Off
datadog.slim_analytics_enabled => Off => Off
datadog.trace.slim_analytics_sample_rate => 1 => 1
datadog.slim_analytics_sample_rate => 1 => 1
datadog.trace.symfony_enabled => On => On
datadog.trace.symfony_analytics_enabled => Off => Off
datadog.symfony_analytics_enabled => Off => Off
datadog.trace.symfony_analytics_sample_rate => 1 => 1
datadog.symfony_analytics_sample_rate => 1 => 1
datadog.trace.web_enabled => On => On
datadog.trace.web_analytics_enabled => Off => Off
datadog.web_analytics_enabled => Off => Off
datadog.trace.web_analytics_sample_rate => 1 => 1
datadog.web_analytics_sample_rate => 1 => 1
datadog.trace.wordpress_enabled => On => On
datadog.trace.wordpress_analytics_enabled => Off => Off
datadog.wordpress_analytics_enabled => Off => Off
datadog.trace.wordpress_analytics_sample_rate => 1 => 1
datadog.wordpress_analytics_sample_rate => 1 => 1
datadog.trace.yii_enabled => On => On
datadog.trace.yii_analytics_enabled => Off => Off
datadog.yii_analytics_enabled => Off => Off
datadog.trace.yii_analytics_sample_rate => 1 => 1
datadog.yii_analytics_sample_rate => 1 => 1
datadog.trace.zendframework_enabled => On => On
datadog.trace.zendframework_analytics_enabled => Off => Off
datadog.zendframework_analytics_enabled => Off => Off
datadog.trace.zendframework_analytics_sample_rate => 1 => 1
datadog.zendframework_analytics_sample_rate => 1 => 1
```

### PR DESCRIPTION
**Pull request by bwoebi**
### Description

Fixes #1474.

### Readiness checklist
- [ ] (only for Members) Changelog has been added to the release document.
- [x] Tests added for this feature/bug.

### Reviewer checklist
- [x] Appropriate labels assigned.
- [x] Milestone is set.
- [x] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

File: tests/Integrations/PCNTL/PCNTLTest.php [hunk 1]
```diff
@@ -81,6 +82,25 @@ public function testCliShortRunningTracingWhenEnabled()
         ]);
     }
 
+    public function testAccessingTracerAfterForkIsUnproblematic()
+    {
+        list($output, $traces) = $this->inCliWithOutput(
+            __DIR__ . '/scripts/access-tracer-after-fork.php',
+            [
+                'DD_TRACE_CLI_ENABLED' => 'true',
+                'DD_TRACE_SHUTDOWN_TIMEOUT' => 5000,
```
Comment (labbati) [inline tests/Integrations/PCNTL/PCNTLTest.php:91]: Is this shutdown necessary or it is just leftover?

File: tests/Common/TracerTestTrait.php [hunk 2]
```diff
@@ -182,7 +182,19 @@ public function inCli($scriptPath, $customEnvs = [], $customInis = [], $argument
         return $this->parseTracesFromDumpedData();
     }
 
-    public function executeCli($scriptPath, $customEnvs = [], $customInis = [], $arguments = '')
+    /**
+     * This method executes a single script with the provided configuration.
+     */
+    public function inCliWithOutput($scriptPath, $customEnvs = [], $customInis = [], $arguments = '')
```
Comment (labbati) [inline tests/Common/TracerTestTrait.php:188]: [Non blocking] Since there are only 5 usages of the original `inCli` I think we could instead:
1. invert the return order from this method to `[$this->parseTracesFromDumpedData(), $this->executeCli($scriptPath, $customEnvs, $customInis, $arguments, true)]`;
2. replace the five usages of `$traces = ...->inCli(...);` with `list($traces) = ...->inCli(...);`

I think some less code to maintain, what do you think?

**Review by labbati — DISMISSED** [review]
I have just a couple of non blocking comments, hence the approval.
Thank you @bwoebi

File: tests/Integrations/PCNTL/PCNTLTest.php (hunk 1 above)
Comment (bwoebi) [reply tests/Integrations/PCNTL/PCNTLTest.php:91]: All the other tests are using it as well, hence I included it (blindly).

File: tests/Common/TracerTestTrait.php (hunk 2 above)
Comment (bwoebi) [reply tests/Common/TracerTestTrait.php]: Done, feel free to re-ack and possibly consider inclusion in 0.69.0 as well?

Comment (labbati) [reply tests/Common/TracerTestTrait.php]: I'd say that 0.69.0 can be released without this, since it would mean postposing one more day for a use case that is not common. 0.70.0 will be out shortly in any case.

File: tests/Integrations/PCNTL/PCNTLTest.php (hunk 1 above)
Comment (labbati) [reply tests/Integrations/PCNTL/PCNTLTest.php:91]: Will take a note t look into it, maybe is not necessary anymore (I'd say hopefully) :)

**Review by labbati — APPROVED** [review]
LGTM

**Review by SammyK — APPROVED** [review]
LGTM 👍
