### PR TITLE
Fix #2174: Can't pass less args to an untyped function than originally passed

### LINKED ISSUE #2174: [Bug]: Can't pass less args to an untyped function than originally passed (minus extra args)
### Bug report

```
Can't pass less args to an untyped function than originally passed (minus extra args) in /opt/datadog-php/dd-trace-sources/bridge/_generated_integrations.php:2054
```

### PHP version

8.1

### Tracer or profiler version

0.90.0

### Installed extensions

_No response_

### Output of `phpinfo()`

_No response_

### Upgrading from

0.89.1

### PR DESCRIPTION
**Pull request by bwoebi**
### Description

Fixes an issue with JIT.

### Readiness checklist
- [ ] (only for Members) Changelog has been added to the release document.
- [ ] Tests added for this feature/bug.

### Reviewer checklist
- [ ] Appropriate labels assigned.
- [ ] Milestone is set.
- [ ] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

**Review by PROFeNoM — APPROVED** [review]
LGTM 😃

File: ext/hook/uhook.c [hunk 1]
```diff
@@ -656,7 +656,7 @@ ZEND_METHOD(DDTrace_HookData, overrideArguments) {
         RETURN_FALSE;
     }
 
-    if (ZEND_USER_CODE(func->type) && hookData->execute_data->opline > func->op_array.opcodes + zend_hash_num_elements(args)) {
+    if (ZEND_USER_CODE(func->type) && MIN(func->common.num_args, passed_args) > zend_hash_num_elements(args)) {
```
Comment (morrisonlevi) [inline ext/hook/uhook.c:659]: Can we get a comment here? I can see what the code is doing, but I don't get why.

Comment (morrisonlevi) [reply ext/hook/uhook.c:661]: Thanks!
