### PR TITLE
Block remote config signals during ftp functions

### LINKED ISSUE #2952: [Bug]: PHP 8.3.13 ftp_fput() gets "Interrupted system call error" unless we use '-d ddtrace.disabled=1' as agument to PHP process call
### Bug report

These were our logs when we started out investigating our FTP upload issue:
```
12:52:58 WARNING   [php] Warning: ftp_fput(): Interrupted system call ["exception" => ErrorException { …}]
12:52:59 WARNING   [php] Warning: ftp_fput(): Connection timed out ["exception" => ErrorException { …}]
12:52:59 WARNING   [php] Warning: ftp_fput(): Accepted data connection ["exception" => ErrorException { …}]
{"message":"Warning: ftp_fput(): Interrupted system call","context":{"exception":{"class":"ErrorException","message":"Warning: ftp_fput(): Interrupted system call","code":0,"file":"/var/www/aud.portal.medido.com/releases/2.5.7/vendor/league/flysystem-ftp/FtpAdapter.php:171"}},"level":300,"level_name":"WARNING","channel":"php","datetime":"2024-11-14T12:52:58.057227+01:00","extra":{}}
{"message":"Warning: ftp_fput(): Connection timed out","context":{"exception":{"class":"ErrorException","message":"Warning: ftp_fput(): Connection timed out","code":0,"file":"/var/www/aud.portal.medido.com/releases/2.5.7/vendor/league/flysystem-ftp/FtpAdapter.php:171"}},"level":300,"level_name":"WARNING","channel":"php","datetime":"2024-11-14T12:52:59.137343+01:00","extra":{}}
{"message":"Warning: ftp_fput(): Accepted data connection","context":{"exception":{"class":"ErrorException","message":"Warning: ftp_fput(): Accepted data connection","code":0,"file":"/var/www/aud.portal.medido.com/releases/2.5.7/vendor/league/flysystem-ftp/FtpAdapter.php:171"}},"level":300,"level_name":"WARNING","channel":"php","datetime":"2024-11-14T12:52:59.173437+01:00","extra":{}}
{"message":"The file could not be uploaded to the ftp server.","context":{"error":"Unable to write file at location: event/daily/2024-11-14T12:52:39+01:00.csv. writing the file failed","file":"event/daily/2024-11-14T12:52:39+01:00.csv"},"level":400,"level_name":"ERROR","channel":"app","datetime":"2024-11-14T12:52:59.177240+01:00","extra":{}}
12:52:59 ERROR     [app] The file could not be uploaded to the ftp server. ["error" => "Unable to write file at location: event/daily/2024-11-14T12:52:39+01:00.csv. writing the file failed","file" => "event/daily/2024-11-14T12:52:39+01:00.csv"]
{"message":"Finished data export for collector <App\\DataExport\\Collector\\EventDataCollector> and target <App\\DataExport\\Target\\FtpDataTarget>.","context":{},"level":200,"level_name":"INFO","channel":"app","datetime":"2024-11-14T12:52:59.181522+01:00","extra":{}}
12:52:59 INFO      [app] Finished data export for collector <App\DataExport\Collector\EventDataCollector> and target <App\DataExport\Target\FtpDataTarget>.
```

This consistently went wrong in our process unless used something like this as we workaround `php -d ddtrace.disabled=1 some-script-handling-ftp-upload.php`.

### PHP version

8.3.13

### Tracer or profiler version

1.4.2

### Installed extensions

_No response_

### Output of `phpinfo()`

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
ddappsec
ddtrace
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
imap
intl
json
libxml
mbstring
mongodb
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
random
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
ddappsec
ddtrace

### Upgrading from

not applicable

### PR DESCRIPTION
**Pull request by bwoebi**
These are sensitive to EINTR, so block the signal during their execution.

Fixes #2952.

### CODE REVIEW

**Review by iamluc — APPROVED** [review]

File: ext/handlers_signal.c [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+ */
+static void dd_handle_signal(zif_handler original_function, INTERNAL_FUNCTION_PARAMETERS) {
+    sigset_t x;
+    sigemptyset(&x);
+    sigaddset(&x, SIGVTALRM);
+    sigprocmask(SIG_BLOCK, &x, NULL);
+
+    original_function(INTERNAL_FUNCTION_PARAM_PASSTHRU);
+
+    sigprocmask(SIG_UNBLOCK, &x, NULL);
```
Comment (Anilm3) [inline ext/handlers_signal.c:18]: If my understanding is correct, this will re-emit at least one queued signal, meaning that you may not need to call `ddtrace_check_for_new_config_now`.

> If invoking sigprocmask causes any pending signals to be unblocked, at least one of those signals is delivered to the process before sigprocmask returns. The order in which pending signals are delivered is not specified, but you can control the order explicitly by making multiple sigprocmask calls to unblock various signals one at a time. [(reference)](https://www.gnu.org/software/libc/manual/html_node/Process-Signal-Mask.html)

Comment (bwoebi) [reply ext/handlers_signal.c:18]: Interesting, that's really nice. Manpages for non-Linux (e.g. macos) say no such thing, so I'll `#ifndef __linux__` this.
