### PR TITLE
fix(profiling): issues when preloading and non-root php-fpm user are used

### LINKED ISSUE #1919: [BUG] FPM shows warnings about rust errors when activating profiler
### Bug description

We activated the datadog profiler in our php applications, but FPM reports a warning about an error in rust 👇 

```
WARNING: child 77 said into stderr: "thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:1311:40"
WARNING: child 77 said into stderr: "stack backtrace:"
WARNING: child 77 said into stderr: "   0:     0x7f4043390f74 - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5"
WARNING: child 77 said into stderr: "   1:     0x7f4043390f74 - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5"
WARNING: child 77 said into stderr: "   2:     0x7f4043390f74 - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5"
WARNING: child 77 said into stderr: "   3:     0x7f4043390f74 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22"
WARNING: child 77 said into stderr: "   4:     0x7f40431a556c - core::fmt::write::he803f0f418caf762"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17"
WARNING: child 77 said into stderr: "   5:     0x7f404338ba1a - std::io::Write::write_fmt::h70bc45872f37e7bb"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15"
WARNING: child 77 said into stderr: "   6:     0x7f4043393a06 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5"
WARNING: child 77 said into stderr: "   7:     0x7f4043393a06 - std::sys_common::backtrace::print::h359300b4a7fccf65"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9"
WARNING: child 77 said into stderr: "   8:     0x7f4043393a06 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22"
WARNING: child 77 said into stderr: "   9:     0x7f4043393726 - std::panicking::default_hook::h03ca0f22e1d2d25e"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9"
WARNING: child 77 said into stderr: "  10:     0x7f40433941f6 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17"
WARNING: child 77 said into stderr: "  11:     0x7f4043393e9c - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:586:13"
WARNING: child 77 said into stderr: "  12:     0x7f40433914b4 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18"
WARNING: child 77 said into stderr: "  13:     0x7f4043393c2d - rust_begin_unwind"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5"
WARNING: child 77 said into stderr: "  14:     0x7f4043178643 - core::panicking::panic_fmt::he1bbc7336d49a357"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14"
WARNING: child 77 said into stderr: "  15:     0x7f404317850d - core::panicking::panic::h4241c5ccea17faca"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5"
WARNING: child 77 said into stderr: "  16:     0x7f40431c19d9 - core::option::Option<T>::unwrap::h0af1abade8f69c20"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:752:21"
WARNING: child 77 said into stderr: "  17:     0x7f40431c19d9 - std::thread::JoinInner<T>::join::h51bbd40ab6e6b0a8"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:1311:9"
WARNING: child 77 said into stderr: "  18:     0x7f40431c19d9 - std::thread::JoinHandle<T>::join::hd7eb153ed30bac93"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:1443:9"
WARNING: child 77 said into stderr: "  19:     0x7f40431c9851 - datadog_php_profiling::profiling::Profiler::stop::hd9d5d1320e2d4d07"
WARNING: child 77 said into stderr: "                               at /home/circleci/datadog/profiling/src/profiling.rs:724:27"
WARNING: child 77 said into stderr: "  20:     0x7f40431c12ed - datadog_php_profiling::mshutdown::h53825f379a205901"
WARNING: child 77 said into stderr: "                               at /home/circleci/datadog/profiling/src/lib.rs:881:9"
WARNING: child 77 said into stderr: "  21:     0x55d813befdff - <unknown>"
WARNING: child 77 said into stderr: "  22:     0x55d813be8570 - <unknown>"
WARNING: child 77 said into stderr: "  23:     0x55d813bfbef9 - zend_hash_graceful_reverse_destroy"
WARNING: child 77 said into stderr: "  24:     0x55d813be9907 - <unknown>"
WARNING: child 77 said into stderr: "  25:     0x55d813b84c42 - php_module_shutdown"
WARNING: child 77 said into stderr: "  26:     0x55d813a3d683 - <unknown>"
WARNING: child 77 said into stderr: "  27:     0x7f40499f0eb0 - __libc_start_call_main"
WARNING: child 77 said into stderr: "  28:     0x7f40499f0f60 - __libc_start_main_alias_2"
WARNING: child 77 said into stderr: "  29:     0x55d813a3f0c5 - _start"
WARNING: child 77 said into stderr: "  30:                0x0 - <unknown>"
WARNING: child 77 said into stderr: "fatal runtime error: failed to initiate panic, error 5"
WARNING: child 77 exited on signal 9 (SIGKILL) after 191.615477 seconds from start
```

This error leads to FPM becoming unresponsive after a while and I'm not sure how to resolve this. 

Datadog is installed inside docker via the following command

```
RUN curl -A "Docker" -o /tmp/datadog-setup.php -D - -L -s https://github.com/DataDog/dd-trace-php/releases/download/0.84.0/datadog-setup.php \
    && php /tmp/datadog-setup.php --php-bin=all --enable-profiling
```

### PHP version

```
PHP 8.1.15 (cli) (built: Jan 31 2023 15:13:17) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.15, Copyright (c), by Zend Technologies
    with ddtrace v0.84.0, Copyright Datadog, by Datadog
    with datadog-profiling v0.13.0, Copyright Datadog, by Datadog
    with ddappsec v0.6.0, Copyright Datadog, by Datadog
```

### Tracer version

```
0.84.0
```

### Installed extensions

```
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
datadog-profiling
date
ddappsec
ddtrace
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
grpc
hash
iconv
igbinary
intl
json
libxml
mbstring
memcached
msgpack
newrelic
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
readline
redis
Reflection
session
SimpleXML
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
datadog-profiling
ddappsec
ddtrace
```

### OS info

```
NAME="AlmaLinux"
VERSION="9.1 (Lime Lynx)"
VERSION_ID="9.1"
PRETTY_NAME="AlmaLinux 9.1 (Lime Lynx)"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```

#### Output of phpinfo() (ddtrace >= 0.47.0)

DATADOG TRACER CONFIGURATION

```json
{
    "date": "2023-02-10T11:23:37Z",
    "os_name": "Linux web-7d6f5865bb-czsjj 5.15.58-flatcar #1 SMP Wed Aug 3 19:35:04 -00 2022 x86_64",
    "os_version": "5.15.58-flatcar",
    "version": "0.84.0",
    "lang": "php",
    "lang_version": "8.1.14",
    "env": "production",
    "enabled": true,
    "service": "web-blue",
    "enabled_cli": false,
    "agent_url": "unix:\/\/\/var\/run\/datadog\/apm.socket",
    "debug": false,
    "analytics_enabled": false,
    "sample_rate": 1,
    "sampling_rules": [],
    "tags": [],
    "service_mapping": [],
    "distributed_tracing_enabled": true,
    "priority_sampling_enabled": true,
    "dd_version": "datadog-profiler",
    "architecture": "x86_64",
    "sapi": "fpm-fcgi",
    "datadog.trace.request_init_hook": "\/opt\/datadog\/dd-library\/0.84.0\/dd-trace-sources\/bridge\/dd_wrap_autoloader.php",
    "open_basedir_configured": false,
    "uri_fragment_regex": null,
    "uri_mapping_incoming": null,
    "uri_mapping_outgoing": null,
    "auto_flush_enabled": false,
    "generate_root_span": true,
    "http_client_split_by_domain": false,
    "measure_compile_time": true,
    "report_hostname_on_root_span": false,
    "traced_internal_functions": null,
    "auto_prepend_file_configured": false,
    "integrations_disabled": "default",
    "enabled_from_env": true,
    "opcache.file_cache": null
}
```
image

### PR DESCRIPTION
**Pull request by morrisonlevi**
### Description

Fixes #1919. An issue occurred when preloading and a non-root user for php-fpm were combined, and eventually php-fpm would hang when the Profiler's channels were full. The full channel was worked around in a previous commit that landed in dd-trace-php v0.85.0, but this PR addresses the core issue so that profiles will actually get sent. Sampling will no longer occur when preloading is happening.

This adds a `CFG_PRELOAD` define for C and `cfg(php_preload)` for Rust, which match. They are made by the `build.rs` script, and are based on PHP version (PHP 7.4+ has preloading).

Bumps the profiling version to v0.15.0.

In CI, this changes the `cargo build` and `cargo test` type of jobs to use devtoolset-7 if it's present. This was required in a previous version of the PR which used `stdatomic.h`, but the newer toolchain is likely preferred anyway, so I've kept it even though it's no longer required.

### Readiness checklist
- [x] Changelog has been added to the release document.
- [ ] Tests added for this feature/bug.

### Reviewer checklist
- [x] Appropriate labels assigned.
- [x] Milestone is set.

### CODE REVIEW

File: profiling/src/php_ffi.c [hunk 1]
```diff
@@ -23,6 +27,37 @@ static ddtrace_profiling_context noop_get_profiling_context(void) {
     return (ddtrace_profiling_context){0, 0};
 }
 
+#if CFG_PRELOAD // defined by build.rs
+static atomic_bool _is_post_startup = false;
```
Comment (bwoebi) [inline profiling/src/php_ffi.c:31]: Is there a specific reason for atomics here? This is minit-stage, during which nothing must ever be parallel.

File: profiling/build.rs [hunk 2]
```diff
@@ -161,6 +166,43 @@ fn generate_bindings(php_config_includes: &str) {
         .expect("bindings to be written successfully");
 }
 
+fn cfg_preload() -> bool {
+    let output = Command::new("php")
+        .arg("-r")
+        .arg("echo (PHP_VERSION_ID >= 70400) ? 1 : 0, PHP_EOL;")
```
Comment (bwoebi) [inline profiling/build.rs:172]: Is there a specific reason why we invoke php here, instead of php-config? Specifically `php-config --vernum`, which also can be used for `cfg_php_major_version`.

File: profiling/src/php_ffi.c (hunk 1 above)
Comment (morrisonlevi) [reply profiling/src/php_ffi.c:31]: I edited the original PR description, but it was maybe after you already looked:
> This isn't strictly necessary in the current state of the PR. In a previous state, it tried accessing the atomic global directly from Rust, which would have made this necessary. However, bindgen was choking on atomic_bool and _Atomic(_Bool) so I switched it. I didn't see a reason to undo this aspect, in case bindgen improves in the future.

File: profiling/build.rs (hunk 2 above)
Comment (morrisonlevi) [reply profiling/build.rs:172]: No, no reason. I suppose we can change it. Does `php-config` have anything for telling us if it's ZTS or not? IIRC it doesn't, you'd have to parse it from `php -v` or similar.

File: profiling/src/php_ffi.c (hunk 1 above)
Comment (bwoebi) [reply profiling/src/php_ffi.c:31]: Yeah, hadn't seen that. I get that rust needs it for safe code, but I prefer at least not declaring something as atomic which may never need atomic semantics.
But I won't insist.

File: profiling/build.rs (hunk 2 above)
Comment (morrisonlevi) [reply profiling/build.rs:172]: > parse it in rust code instead of bash? 
🤦🏻

Comment (morrisonlevi) [reply profiling/build.rs]: Fixed, since as you pointed out the `cfg_php_major_version` and `cfg_preload` routines can use the same source.

File: profiling/src/php_ffi.c (hunk 1 above)
Comment (morrisonlevi) [reply profiling/src/php_ffi.c]: Eh, it was easy enough to get rid of.

**Review by realFlowControl — APPROVED** [review]
