### PR TITLE
Remove Symfony Command Hook After Execution

### LINKED ISSUE #2427: [Bug]: Memory leaking with hooks limit reached after upgrade from 0.90.0 to 0.91.2
### Bug report

k8 pods with long running processes start getting OOM after DD extension upgrade from `0.90.0` to `0.91.2`.
DD dashboards indicate leaking memory.
Log received:
```
Could not add hook to ApiPlatform\Action\PlaceholderAction::__invoke with more than datadog.trace.hook_limit = 100 installed hooks in /opt/datadog/dd-library/0.91.2/dd-trace-sources/bridge/_generated_integrations.php on line 3860; This message is only displayed once. Specify DD_TRACE_ONCE_LOGS=0 to show all messages.
```



### PHP version

8.2.13

### Tracer or profiler version

0.91.2

### Installed extensions

```
[PHP Modules]                                                                                                                                                                                                
amqp                                                                                                                                                                                                         
bcmath                                                                                                                                                                                                       
Core                                                                                                                                                                                                         
ctype
curl
date
ddappsec
ddtrace
dom
fileinfo
filter
ftp
gd
gmp
hash
iconv
igbinary
intl
json
libxml
mbstring
mcrypt
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
random
readline
redis
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
ddappsec
ddtrace
```

### Output of `phpinfo()`

[o.txt](https://github.com/DataDog/dd-trace-php/files/13685361/o.txt)


### Upgrading from

`0.90.0` -> `0.91.2`

### PR DESCRIPTION
**Pull request by PROFeNoM**
### Description

Fixes #2427

This PR should have been included with #2436

TL;DR of the issue:
```
Could not add hook to MyCommand::run with more than datadog.trace.hook_limit = 100 installed hooks in /opt/datadog-php/dd-trace-sources/bridge/_generated_integrations.php on line 4014; This message is only displayed once. Specify DD_TRACE_ONCE_LOGS=0 to show all messages.
```

The current implementation of the command hooks adds a hook to a `<scope>::run` if it wasn't already added. This could, theoretically, lead to multiple hooks added when considering numerous inheritors.

About the fix: Considering that in the previous version the hook was made on `Symfony\Component\Console\Command\Command::__construct`, it means that `$scope` fundamentally represents a `Symfony\Component\Console\Command\Command` instance. From this, the new implementation directly hooks `Symfony\Component\Console\Command\Command::run` instead of adding a seemingly unnecessary intermediary step.

### Reviewer checklist
- [ ] Test coverage seems ok.
- [ ] Appropriate labels assigned.

### CODE REVIEW

File: src/Integrations/Integrations/Symfony/SymfonyIntegration.php [hunk 1]
```diff
@@ -248,46 +248,36 @@ function ($This, $scope, $args) {
...
-            '__construct',
-            null,
-            function ($This, $scope) use (&$symfonyCommandsIntegrated, $integration) {
-                if (isset($symfonyCommandsIntegrated[$scope])) {
-                    return;
-                }
-
-                $symfonyCommandsIntegrated[$scope] = true;
-
-                \DDTrace\trace_method($scope, 'run', [
```
Comment (bwoebi) [inline src/Integrations/Integrations/Symfony/SymfonyIntegration.php:263]: I assume this was an artifact of pre-historical times when we had no support for abstract method hooks?

At a glance this fix looks pretty good to me.

**Review by bwoebi — APPROVED** [review]
