### PR TITLE
fix(prof): crash on PHP 8.4

### LINKED ISSUE #3012: [Bug]: Segfault when profiling is enabled in php 8.4.1 on Ubuntu
### Bug report

When running Symfony 6.4 in PHP8.4 with the profiler enabled, the PHP-FPM process exits with a segfault.

The output of `dmesg | grep segfault | tail -10` is:

```
[354225.435912] dd-ipc-helper[3600702]: segfault at 407cd6 ip 0000000000407cd6 sp 00007a2ba0fff8c8 error 14 in memfd:spawn_worker_trampoline (deleted)[601000+1000] likely on CPU 5 (core 1, socket 0)
[354244.458155] dd-ipc-helper[2489378]: segfault at 407bd6 ip 0000000000407bd6 sp 00007a25d65ffc18 error 14 in memfd:spawn_worker_trampoline (deleted)[601000+1000] likely on CPU 5 (core 1, socket 0)
```

The application works properly with PHP 8.3, but is just fails with PHP 8.4. When I disable the `datadog-profiling.so` package, FPM works properly, but the profiling is disabled which we use quite extensively.

If more information is necessary, please let me know and I'll be happy to provide.

### PHP version

8.4.1

### Tracer or profiler version

1.5.1

### Installed extensions

```
[PHP Modules]
amqp
apcu
bcmath
calendar
Core
ctype
curl
datadog-profiling
date
ddappsec
ddtrace
dom
excimer
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
random
readline
redis
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
datadog-profiling
ddappsec
ddtrace
```

### Output of `phpinfo()`

```json
{ "date": "2024-12-21T15:56:49Z", "os_name": "Linux legionelladossier-migration-testing 6.8.0-51-generic #52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec 5 13:09:44 UTC 2024 x86_64", "os_version": "6.8.0-51-generic", "version": "1.5.1", "lang": "php", "lang_version": "8.4.0RC4", "env": "staging", "enabled": true, "service": "LegionellaDossier", "enabled_cli": true, "agent_url": "unix:\/\/\/var\/run\/datadog\/apm.socket", "debug": false, "analytics_enabled": false, "sample_rate": 1, "sampling_rules": [], "tags": [], "service_mapping": [], "distributed_tracing_enabled": true, "dd_version": "1", "architecture": "x86_64", "instrumentation_telemetry_enabled": true, "sapi": "fpm-fcgi", "datadog.trace.sources_path": "\/opt\/datadog\/dd-library\/1.1.0\/dd-trace-sources\/src", "open_basedir_configured": false, "uri_fragment_regex": null, "uri_mapping_incoming": null, "uri_mapping_outgoing": null, "auto_flush_enabled": false, "generate_root_span": true, "http_client_split_by_domain": true, "measure_compile_time": true, "report_hostname_on_root_span": false, "traced_internal_functions": null, "enabled_from_env": true, "opcache.file_cache": null, "sidecar_trace_sender": true }
```

Image

### Upgrading from

I'm upgrading from PHP8.3, and there it worked properly. I used to have PHP8.4.0RC4 installed, but now php 8.4.1 is installed. I did redownload the installer, and ran the installer once more.

### PR DESCRIPTION
**Pull request by morrisonlevi**
### Description

Fixes #3012. The profiler can crash on PHP 8.4 when walking the stack for any kind of sample type. The internals upgrading guide says:

```
* zend_get_internal_function_extension_handle[s]() must now be used over
  zend_get_op_array_extension_handle[s]() when registering run_time_cache slots
  for internal functions. If you need a cache slot for both internal and user
  functions, you may obtain a slot for each through the corresponding function.
```

So we call this now as well and use that handle instead of the user handle for internal functions.

~Note that there is a piece in this PR which shouldn't ship: an increase to the debug level. I did this so I can inspect variables and such with the artifacts from CI. This should be reverted before merging.~ Reverted. PR is ready for review.

### Reviewer checklist
- [ ] Test coverage seems ok.
- [x] Appropriate labels assigned.

### CODE REVIEW

File: profiling/src/php_ffi.c [hunk 1]
```diff
@@ -324,14 +331,22 @@ void ddog_php_prof_function_run_time_cache_init(const char *module_name) {
...
 #else
-    ddog_php_prof_run_time_cache_handle =
+    _user_run_time_cache_handle =
+        zend_get_op_array_extension_handles(module_name, 2);
+
+#if PHP_VERSION_ID >= 80400
+    // On PHP 8.4+, the internal cache slots need to be registered separately
+    // from the user ones.
+    _internal_run_time_cache_handle =
         zend_get_op_array_extension_handles(module_name, 2);
```
Comment (bwoebi) [inline profiling/src/php_ffi.c:346]: You meant to call zend_get_internal_function_extension_handle here? You're calling op_array again.

**Review by realFlowControl — APPROVED** [review]
