### PR TITLE
Restore support for manual distributed tracing

### LINKED ISSUE #1292: [BUG] x-datadog-sampling-priority seems to be ignored
### Bug description
We have a long-running process (PHP) running which does read AMQP messages and traces the process when a span context is present on the message. Tracing works as expected, but whenever the `x-datadog-sampling-priority` is set to 0, the process still gets traced. All other processes in the distributed chain (non-PHP) seem to respect this.

### PHP version
PHP 7.4.21 (cli) (built: Jul 22 2021 03:08:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.21, Copyright (c), by Zend Technologies
    with ddtrace v0.62.1, Copyright Datadog, by Datadog
    with blackfire v1.60.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire
    
### Installed extensions
[PHP Modules]
apcu
bcmath
blackfire
Core
ctype
curl
date
ddtrace
dom
fileinfo
filter
ftp
gd
grpc
hash
iconv
intl
json
libxml
mbstring
mongodb
mysqli
mysqlnd
OAuth
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
protobuf
readline
redis
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
blackfire
ddtrace

### OS info
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

#### Output of phpinfo() (ddtrace >= 0.47.0)
Datadog PHP tracer extension
For help, check out the documentation at https://docs.datadoghq.com/tracing/languages/php/
(c) Datadog 2020

Datadog tracing support => enabled
Version => 0.62.1
DATADOG TRACER CONFIGURATION => {"date":"2021-08-12T14:04:24Z","os_name":"Linux 4.9.0-12-amd64 SMP Debian 4.9.210-1 (2020-01-20) x86_64","os_version":"4.9.0-12-amd64","version":"0.62.1","lang":"php","lang_version":"7.4.21","env":"dev-1","enabled":true,"service":null,"enabled_cli":true,"agent_url":"<redacted>","debug":true,"analytics_enabled":false,"sample_rate":1.000000,"sampling_rules":null,"tags":null,"service_mapping":null,"distributed_tracing_enabled":true,"priority_sampling_enabled":true,"architecture":"x86_64","sapi":"cli","ddtrace.request_init_hook":"/opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php","open_basedir_configured":false,"uri_fragment_regex":null,"uri_mapping_incoming":null,"uri_mapping_outgoing":null,"auto_flush_enabled":true,"generate_root_span":false,"http_client_split_by_domain":false,"measure_compile_time":true,"report_hostname_on_root_span":false,"traced_internal_functions":null,"auto_prepend_file_configured":false,"integrations_disabled":null,"enabled_from_env":true,"opcache.file_cache":null}

                               Diagnostics
Diagnostic checks => passed

Directive => Local Value => Master Value
ddtrace.disable => Off => Off
ddtrace.request_init_hook => /opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php => /opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php
ddtrace.cgroup_file => /proc/self/cgroup => /proc/self/cgroup

### PR DESCRIPTION
**Pull request by bwoebi**
### Description

We broke the manual distributed tracing handling when moving the distributed tracing to internal.

Fixes #1292.

### Readiness checklist
- [x] (only for Members) Changelog has been added to the release document.
- [x] Tests added for this feature/bug.

### Reviewer checklist
- [ ] Appropriate labels assigned.
- [ ] Milestone is set.
- [ ] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

**Review by labbati — COMMENTED** [review]
This LGTM for the PHP part!

File: ext/php8/ddtrace.c [hunk 1]
```diff
@@ -165,6 +165,13 @@ ZEND_BEGIN_ARG_INFO_EX(arginfo_dd_trace_close_span, 0, 0, 0)
 ZEND_ARG_INFO(0, finish_time)
 ZEND_END_ARG_INFO()
 
+ZEND_BEGIN_ARG_INFO_EX(arginfo_dd_trace_set_distributed_tracing_context, 0, 0, 2)
+ZEND_ARG_INFO(0, trace_id)
+ZEND_ARG_INFO(0, parent_id)
+ZEND_ARG_INFO(0, origin)
+ZEND_ARG_INFO(0, tags)
```
Comment (SammyK) [inline ext/php8/ddtrace.c:172]: Back in the day, `origin` did not exist as a propagated header. That makes me think that we are likely to see new values supported in distributed tracing contexts in the future. I think trace ID and parent ID make sense as arguments, but I wonder if `origin` should be combined with `tags` as a generic vehicle to support new values in the future without having to update the API.

Comment (bwoebi) [reply ext/php8/ddtrace.c:172]: I guess, if we now freshly introduced `origin`, after having `tags`, it would've gone into tags. But currently it is separate and probably should be reflected in the API as such as well?

**Review by krakjoe — APPROVED** [review]
