### PR TITLE
Handle absolute paths in extension_dir containing forward slashes

### LINKED ISSUE #2786: [Bug]: cannot install datadog on windows php
### Bug report

C:\Users\eod014\Downloads>php datadog-setup.php --php-bin=all
Searching for available php binaries, this operation might take a while.
Downloading installable archive from https://github.com/DataDog/dd-trace-php/releases/download/1.2.0/dd-library-php-1.2.0-x86_64-windows.tar.gz.
This operation might take a while.

Notice: Undefined variable: http_response_header in C:\Users\eod014\Downloads\datadog-setup.php on line 1470

Call Stack:
    0.0023     719176   1. {main}() C:\Users\eod014\Downloads\datadog-setup.php:0
    0.0023     719984   2. main() C:\Users\eod014\Downloads\datadog-setup.php:2363
    0.0024     721224   3. install($options = ['uninstall' => FALSE, 'php-bin' => [0 => 'all'], 'install-dir' => 'C:\\Program Files\\Datadog\\PHP Tracer/dd-library', 'extension-dir' => NULL, 'enable-appsec' => FALSE, 'enable-profiling' => FALSE]) C:\Users\eod014\Downloads\datadog-setup.php:72
    6.9041     724160   4. download($url = 'https://github.com/DataDog/dd-trace-php/releases/download/1.2.0/dd-library-php-1.2.0-x86_64-windows.tar.gz', $destination = 'C:\\Users\\eod014\\AppData\\Local\\Temp/dd-install/dd-library-php-x86_64-windows.tar.gz') C:\Users\eod014\Downloads\datadog-setup.php:494

Warning: Invalid argument supplied for foreach() in C:\Users\eod014\Downloads\datadog-setup.php on line 1470

Call Stack:
    0.0023     719176   1. {main}() C:\Users\eod014\Downloads\datadog-setup.php:0
    0.0023     719984   2. main() C:\Users\eod014\Downloads\datadog-setup.php:2363
    0.0024     721224   3. install($options = ['uninstall' => FALSE, 'php-bin' => [0 => 'all'], 'install-dir' => 'C:\\Program Files\\Datadog\\PHP Tracer/dd-library', 'extension-dir' => NULL, 'enable-appsec' => FALSE, 'enable-profiling' => FALSE]) C:\Users\eod014\Downloads\datadog-setup.php:72
    6.9041     724160   4. download($url = 'https://github.com/DataDog/dd-trace-php/releases/download/1.2.0/dd-library-php-1.2.0-x86_64-windows.tar.gz', $destination = 'C:\\Users\\eod014\\AppData\\Local\\Temp/dd-install/dd-library-php-x86_64-windows.tar.gz') C:\Users\eod014\Downloads\datadog-setup.php:494

ERROR: Error while downloading the installable archive from https://github.com/DataDog/dd-trace-php/releases/download/1.2.0/dd-library-php-1.2.0-x86_64-windows.tar.gz

### PHP version

7.4.33

### Tracer or profiler version

NA

### Installed extensions

_No response_

### Output of `phpinfo()`

_No response_

### Upgrading from

_No response_

### PR DESCRIPTION
**Pull request by bwoebi**
`extension_dir = c:/php/ext` is also valid on Windows.

Fixes #2786.

### CODE REVIEW

File: datadog-setup.php [hunk 1]
```diff
@@ -1574,7 +1574,7 @@ function ini_values($binary)
 
     if ($found[EXTENSION_DIR] == "") {
         $found[EXTENSION_DIR] = dirname(PHP_BINARY);
-    } elseif ($found[EXTENSION_DIR][0] != "/" && (!IS_WINDOWS || !preg_match('~^([A-Z]:|\\\\)\\\\~i', $found[EXTENSION_DIR]))) {
+    } elseif ($found[EXTENSION_DIR][0] != "/" && (!IS_WINDOWS || !preg_match('~^([A-Z]:[\\\\/]|\\\\{2})~i', $found[EXTENSION_DIR]))) {
```
Comment (iamluc) [inline datadog-setup.php:1577]: Shouldn't it be `~^([A-Z]:[\\/]|\\{2})~i`?

- `[\\\\/]` changed to `[\\/]`. No need to repeat `\\` twice in the list of allowed chars
- `\\\\{2}` changed to `\\{2}`. Otherwise we must match `\` 3 times

Comment (bwoebi) [reply datadog-setup.php:1577]: `'\\'` in a string will be equivalent to a single \.
However in regex, you need to escape all metacharacters as well. Thus doubling the \\.

**Review by iamluc — APPROVED** [review]
